name: Compile typescript

on:
    push:
        branches: ['main']

jobs:
    Compile:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [latest]

        steps:
            - uses: actions/checkout@latest
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@latest
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm i
            - name: Compile
              run: npm run compile
            - name: Upload artifact
              uses: actions/upload-artifact@latest
              with:
                  name: artifact
                  path: out/
    Push:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [latest]

        steps:
            - uses: actions/checkout@latest
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: momualt/justabot:latest
